################
# Options

set-option -s escape-time 0
set-option -g history-limit 50000
set-option -g display-time 4000
set-option -g status-interval 1
set-option -g focus-events on
set-option -g aggressive-resize on
set-option -g mouse on
set-option -g mode-keys vi
set-option -g detach-on-destroy off
set-option -g set-titles on
set-option -g set-titles-string "#S / #W"
set-option -g default-terminal "xterm-ghostty"
set-option -g default-command "nu"
set-option -sa terminal-overrides ",xterm-256color:Tc"
set-option -ga terminal-features "*:hyperlinks"
set-option -gq allow-passthrough on
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on


################
# Keys

# Set prefix
set-option -g prefix "`"
set-option -g prefix2 C-b
bind-key "`" send-prefix
bind-key C-b send-prefix -2

# Vim-style splits
bind-key \\ split-window -h -c "#{pane_current_path}"
bind-key | split-window -hb -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
bind-key _ split-window -vb -c "#{pane_current_path}"

# Toggle terminal
bind-key "Enter" if-shell "[ $(tmux list-windows | wc -l) -eq 1 ]" "new-window" "last-window"

# Sessionizer
bind-key o display-popup -E "nu -l -c 'tms'"
bind-key a run-shell "nu -l -c 'tms ~/scratch'"

# Other keybindings
bind-key r source-file ~/.config/tmux/tmux.conf
bind-key "Space" switch-client -l
bind-key e select-layout -E
bind-key x kill-pane
bind-key X kill-session

# Copy mode
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi WheelUpPane send-keys -X -N 2 scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X -N 2 scroll-down


################
# Style

# Status bar style
set-option -g status-position bottom
set-option -g status-style bg="#2f312c",fg="#f1e9d2"

# Inactive window labels
set-option -g window-status-style bg="#2f312c",fg="#a3a7a1"
set-option -g window-status-format " #{window_index}:#W#F"

# Active window label is highlighted. Append -Z if a pane is zoomed.
set-option -g window-status-current-style bg="#2f312c",fg="#f1e9d2"
set-option -g window-status-current-format " (#W#{?#{==:#F,*},,#F})"

# Set style of tmux "popups", like the scroll position indicator
set-option -g mode-style bg="#f1e9d2",fg="#2f312c",bold
set-option -g message-style bg="#f1e9d2",fg="#2f312c"
set-option -g message-command-style bg="#f1e9d2",fg="#2f312c"

# Pane separation colors
set-option -g pane-active-border-style fg="colour242"
set-option -g pane-border-style fg="colour242"

# Statuses
set-option -g status-right-length 50
set-option -g status-left-length 50
set-option -g status-left "#[bg=#2f312c,fg=#f1e9d2] [#{session_name}] "
set-option -g status-right "#H #{?#{==:#{pane_mode},copy-mode},#[bg=#f1e9d2]#[fg=black],}#{?client_prefix,#[bg=green]#[fg=black]  ,  }"
